# Generated by Django 5.2.11 on 2026-03-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_offer_product_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='electronincs', max_length=50),
        ),
    ]
