# Generated by Django 5.2.11 on 2026-03-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdesc', models.TextField()),
                ('pcategory', models.CharField(max_length=50)),
                ('trending', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('pimage', models.ImageField(default='Default.jpg', upload_to='uploads')),
            ],
        ),
    ]
