# Generated by Django 5.2.11 on 2026-03-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cartmodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
